defaults:
  app:
    workerTableName: WMWorkers
    workerTypeTableName: WMWorkerTypes
    workerTypeErrorTableName: WMWorkerTypeErrors
    errorsExpirationTime: '-4 days' # Anything older than a few days goes away
    provisionerId: worker-manager
  monitoring:
    level: !env LEVEL
  taskcluster:
    rootUrl: !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN
  azure:
    accountId: !env AZURE_ACCOUNT
  server:
    port: !env:number PORT
    env: !env NODE_ENV
    forceSSL: !env:bool FORCE_SSL
    trustProxy: !env:bool TRUST_PROXY
  pulse:
    hostname: !env PULSE_HOSTNAME
    username: !env PULSE_USERNAME
    password: !env PULSE_PASSWORD
    vhost: !env PULSE_VHOST
    namespace: !env PULSE_NAMESPACE
  providers: !env:json PROVIDERS


test:
  server:
    port: 60409
    env: 'development'
    forceSSL: false
    trustProxy: false
  providers:
    testing1:
      implementation: testing
    testing2:
      implementation: testing
    static:
      implementation: static
    google:
      implementation: google
